[project]
name = "kulyk-rust"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "polars>=1.34.0",
    "requests>=2.32.5",
    "ruff>=0.14.0",
]
